import express from 'express';
import { routerMain } from './routers/router.main';
import cors from 'cors';
import { handleError } from './middleware/handle.error';
const port: number = Number(process.env.PORT ?? '8000');
const app = express();
app.use(cors());
app.use(express.json());
app.use(routerMain);
app.use(handleError);
app.listen(port, () => console.log(`server online on http://localhost:${port}`));
